In [3]:
import torch

def demo_tensors():
    """
    Demo of creating tensors in PyTorch with updated numbers:
    - scalar (0-D)
    - vector (1-D)
    - matrix (2-D)
    - 3D tensor
    Returns all four tensors.
    """

    # --- Scalar ---
    scalar = torch.tensor(42)
    # Expected console output:
    # tensor: tensor(42)
    # ndim:   0
    # .item(): 42

    # --- Vector ---
    vector = torch.tensor([2, 3])
    # Expected console output:
    # tensor: tensor([2, 3])
    # ndim:   1
    # shape:  torch.Size([2])

    # --- Matrix ---
    matrix = torch.tensor([
        [1,   4,  9],
        [16, 25, 36],
        [49, 64, 81]
    ])
    # Expected console output:
    # tensor:
    # tensor([[ 1,  4,  9],
    #         [16, 25, 36],
    #         [49, 64, 81]])
    # ndim:   2
    # shape:  torch.Size([3, 3])

    # --- 3D Tensor ---
    tensor3d = torch.tensor([[
        [10, 20],
        [30, 40]
    ]])
    # Expected console output:
    # tensor shape: torch.Size([1, 2, 2])
    # ndim:        3
    # tensor:
    # tensor([[[10, 20],
    #          [30, 40]]])

    return scalar, vector, matrix, tensor3d



s, v, m, t = demo_tensors()
# Uncomment to print during a live run:
print(s, s.ndim, s.item())
print(v, v.ndim, v.shape)
print(m, m.ndim, m.shape)
print(t, t.ndim, t.shape)

tensor(42) 0 42
tensor([2, 3]) 1 torch.Size([2])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]) 2 torch.Size([3, 3])
tensor([[[10, 20],
         [30, 40]]]) 3 torch.Size([1, 2, 2])


In [4]:
import torch

def tensor_playground():
    """
    🎲 A playful tour of common PyTorch tensor creators:
    - Random tensors (uniform 0–1)
    - All zeros and all ones
    - Sequences via arange
    - Like-it templates with zeros_like
    """

    # —————————————————————————
    # 🎰 1) Random Tensor: “Lottery Matrix”
    # —————————————————————————
    torch.manual_seed(42)  # for reproducible “randomness”
    lottery_matrix = torch.rand(size=(2, 5))
    # Expected console output (approx.):
    # tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
    #         [0.6009, 0.2566, 0.7936, 0.9408, 0.9690]])
    # shape: torch.Size([2, 5]), dtype: torch.float32

    # —————————————————————————
    # 🖼️ 2) Random “Image”: “Tiny Color Patch”
    # —————————————————————————
    torch.manual_seed(7)
    tiny_color_patch = torch.rand(size=(4, 4, 3))
    # Expected console output (approx.):
    # tensor([[[0.0871, 0.1071, 0.5080],
    #          [0.6324, 0.4901, 0.8964],
    #          [0.7622, 0.6154, 0.4448],
    #          [0.5196, 0.5969, 0.9684]],
    #         … 3 more rows … ])
    # shape: torch.Size([4, 4, 3]), ndim: 3

    # —————————————————————————
    # 🕳️ 3) All Zeros: “Ghost Grid”
    # —————————————————————————
    ghost_grid = torch.zeros(size=(3, 2))
    # Expected console output:
    # tensor([[0., 0.],
    #         [0., 0.],
    #         [0., 0.]])
    # dtype: torch.float32

    # —————————————————————————
    # ☁️ 4) All Ones: “Cloud Array”
    # —————————————————————————
    cloud_array = torch.ones(size=(2, 4))
    # Expected console output:
    # tensor([[1., 1., 1., 1.],
    #         [1., 1., 1., 1.]])
    # dtype: torch.float32

    # —————————————————————————
    # 🔢 5) Sequence via arange: “Step Ladder”
    # —————————————————————————
    step_ladder = torch.arange(start=5, end=15, step=3)
    # Expected console output:
    # tensor([ 5,  8, 11, 14])
    # dtype: torch.int64

    # —————————————————————————
    # 🪄 6) Texture from Template: zeros_like
    # —————————————————————————
    ladder_zeros = torch.zeros_like(input=step_ladder)
    # Expected console output:
    # tensor([0, 0, 0, 0])
    # dtype: torch.int64  # matches step_ladder’s dtype and shape

    return {
        "lottery_matrix": lottery_matrix,
        "tiny_color_patch": tiny_color_patch,
        "ghost_grid": ghost_grid,
        "cloud_array": cloud_array,
        "step_ladder": step_ladder,
        "ladder_zeros": ladder_zeros
    }


if __name__ == "__main__":
    tensors = tensor_playground()
    # To see live output, you could:
    for name, t in tensors.items():
      print(f"{name} ->", t, "| shape:", t.shape, "| dtype:", t.dtype)

lottery_matrix -> tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332]]) | shape: torch.Size([2, 5]) | dtype: torch.float32
tiny_color_patch -> tensor([[[0.5349, 0.1988, 0.6592],
         [0.6569, 0.2328, 0.4251],
         [0.2071, 0.6297, 0.3653],
         [0.8513, 0.8549, 0.5509]],

        [[0.2868, 0.2063, 0.4451],
         [0.3593, 0.7204, 0.0731],
         [0.9699, 0.1078, 0.8829],
         [0.4132, 0.7572, 0.6948]],

        [[0.5209, 0.5932, 0.8797],
         [0.6286, 0.7653, 0.1132],
         [0.8559, 0.6721, 0.6267],
         [0.5691, 0.7437, 0.9592]],

        [[0.3887, 0.2214, 0.3742],
         [0.1953, 0.7405, 0.2529],
         [0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355]]]) | shape: torch.Size([4, 4, 3]) | dtype: torch.float32
ghost_grid -> tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) | shape: torch.Size([3, 2]) | dtype: torch.float32
cloud_array -> tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

In [5]:
import torch

def dtype_showcase():
    """
    A quick tour of PyTorch dtypes.
    """

    # ——————————————————————
    # 1) 32-bit floating point
    fp32 = torch.tensor([3.14, -1.23], dtype=torch.float32)
    # Expected:
    # tensor([ 3.1400, -1.2300], dtype=torch.float32)

    # ——————————————————————
    # 2) 64-bit floating point
    fp64 = torch.tensor([3.14, -1.23], dtype=torch.float64)
    # Expected:
    # tensor([ 3.1400, -1.2300], dtype=torch.float64)

    # ——————————————————————
    # 3) 16-bit floating point (“half”)
    fp16 = torch.tensor([3.14, -1.23], dtype=torch.float16)
    # Expected:
    # tensor([ 3.1406, -1.2295], dtype=torch.float16)

    # ——————————————————————
    # 4) 16-bit brain floating point
    bf16 = torch.tensor([3.14, -1.23], dtype=torch.bfloat16)
    # Expected:
    # tensor([ 3.1406, -1.2300], dtype=torch.bfloat16)

    # ——————————————————————
    # 5) 32-bit complex
    c32 = torch.tensor([1+2j, 3+4j], dtype=torch.complex32)
    # Expected:
    # tensor([1.+2.j, 3.+4.j], dtype=torch.complex32)

    # ——————————————————————
    # 6) 64-bit complex
    c64 = torch.tensor([1+2j, 3+4j], dtype=torch.complex64)
    # Expected:
    # tensor([1.+2.j, 3.+4.j], dtype=torch.complex64)

    # ——————————————————————
    # 7) 128-bit complex
    c128 = torch.tensor([1+2j, 3+4j], dtype=torch.complex128)
    # Expected:
    # tensor([1.+2.j, 3.+4.j], dtype=torch.complex128)

    # ——————————————————————
    # 8) 8-bit unsigned integer
    u8 = torch.tensor([0, 255], dtype=torch.uint8)
    # Expected:
    # tensor([  0, 255], dtype=torch.uint8)

    # ——————————————————————
    # 9) 16-bit unsigned integer (limited support)
    u16 = torch.tensor([0, 65535], dtype=torch.uint16)
    # Expected:
    # tensor([    0, 65535], dtype=torch.uint16)

    # ——————————————————————
    # 10) 32-bit unsigned integer (limited support)
    u32 = torch.tensor([0, 2**32-1], dtype=torch.uint32)
    # Expected:
    # tensor([        0, 4294967295], dtype=torch.uint32)

    # ——————————————————————
    # 11) 64-bit unsigned integer (limited support)
    u64 = torch.tensor([0, 2**64-1], dtype=torch.uint64)
    # Expected:
    # tensor([                  0, 18446744073709551615], dtype=torch.uint64)

    # ——————————————————————
    # 12) 8-bit signed integer
    i8 = torch.tensor([-128, 127], dtype=torch.int8)
    # Expected:
    # tensor([-128,  127], dtype=torch.int8)

    # ——————————————————————
    # 13) 16-bit signed integer
    i16 = torch.tensor([-32768, 32767], dtype=torch.int16)
    # Expected:
    # tensor([-32768,  32767], dtype=torch.int16)

    # ——————————————————————
    # 14) 32-bit signed integer
    i32 = torch.tensor([-2**31, 2**31-1], dtype=torch.int32)
    # Expected:
    # tensor([-2147483648,  2147483647], dtype=torch.int32)

    # ——————————————————————
    # 15) 64-bit signed integer
    i64 = torch.tensor([-2**63, 2**63-1], dtype=torch.int64)
    # Expected:
    # tensor([-9223372036854775808,  9223372036854775807], dtype=torch.int64)

    # ——————————————————————
    # 16) Boolean
    b = torch.tensor([True, False, True], dtype=torch.bool)
    # Expected:
    # tensor([ True, False,  True])

    # ——————————————————————
    # 17) Quantized 8-bit unsigned (requires quantize_per_tensor)
    q_u8 = torch.quantize_per_tensor(torch.tensor([0.0, 1.0]), scale=0.1, zero_point=10, dtype=torch.quint8)
    # Expected:
    # tensor([10, 20], size=(2,), dtype=torch.quint8, quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

    # ——————————————————————
    # 18) Quantized 8-bit signed
    q_i8 = torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0]), scale=0.5, zero_point=0, dtype=torch.qint8)
    # Expected:
    # tensor([ -2,   0,   2], size=(3,), dtype=torch.qint8, quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)

    # ——————————————————————
    # 19) Quantized 32-bit signed
    q_i32 = torch.quantize_per_tensor(torch.tensor([100.0, 200.0]), scale=1.0, zero_point=0, dtype=torch.qint32)
    # Expected:
    # tensor([100, 200], size=(2,), dtype=torch.qint32, quantization_scheme=torch.per_tensor_affine, scale=1.0, zero_point=0)

    # ——————————————————————
    # 20) Quantized 4-bit unsigned (limited support)
    # torch.quint4x2 packs two 4-bit values per byte; usage is similar:
    # Example placeholder (actual creation API may vary with PyTorch version):
    # q_u4 = torch._empty_affine_quantized((2,), dtype=torch.quint4x2, scale=1.0, zero_point=0)
    # Expected: size=(2,), dtype=torch.quint4x2 ...

    # ——————————————————————
    # 21) 8-bit floating e4m3
    f8_e4m3 = torch.tensor([1.0, -2.0], dtype=torch.float8_e4m3fn)
    # Expected:
    # tensor([ 1.0000, -2.0000], dtype=torch.float8_e4m3fn)

    # ——————————————————————
    # 22) 8-bit floating e5m2
    f8_e5m2 = torch.tensor([1.0, -2.0], dtype=torch.float8_e5m2)
    # Expected:
    # tensor([ 1.0000, -2.0000], dtype=torch.float8_e5m2)

    return {
        "fp32": fp32, "fp64": fp64, "fp16": fp16, "bf16": bf16,
        "c32": c32, "c64": c64, "c128": c128,
        "u8": u8, "u16": u16, "u32": u32, "u64": u64,
        "i8": i8, "i16": i16, "i32": i32, "i64": i64,
        "bool": b, "q_u8": q_u8, "q_i8": q_i8, "q_i32": q_i32,
        # "q_u4": q_u4,  # uncomment if supported
        "f8_e4m3": f8_e4m3, "f8_e5m2": f8_e5m2
    }

if __name__ == "__main__":
    examples = dtype_showcase()
    # Uncomment to print:
    for name, t in examples.items():
      print(f"{name}: {t} | dtype={t.dtype}")

fp32: tensor([ 3.1400, -1.2300]) | dtype=torch.float32
fp64: tensor([ 3.1400, -1.2300], dtype=torch.float64) | dtype=torch.float64
fp16: tensor([ 3.1406, -1.2305], dtype=torch.float16) | dtype=torch.float16
bf16: tensor([ 3.1406, -1.2266], dtype=torch.bfloat16) | dtype=torch.bfloat16
c32: tensor([1.+2.j, 3.+4.j], dtype=torch.complex32) | dtype=torch.complex32
c64: tensor([1.+2.j, 3.+4.j]) | dtype=torch.complex64
c128: tensor([1.+2.j, 3.+4.j], dtype=torch.complex128) | dtype=torch.complex128
u8: tensor([  0, 255], dtype=torch.uint8) | dtype=torch.uint8
u16: tensor([    0, 65535], dtype=torch.uint16) | dtype=torch.uint16
u32: tensor([         0, 4294967295], dtype=torch.uint32) | dtype=torch.uint32
u64: tensor([                   0, 18446744073709551615], dtype=torch.uint64) | dtype=torch.uint64
i8: tensor([-128,  127], dtype=torch.int8) | dtype=torch.int8
i16: tensor([-32768,  32767], dtype=torch.int16) | dtype=torch.int16
i32: tensor([-2147483648,  2147483647], dtype=torch.int32) | dty

/tmp/ipython-input-5-524841642.py:34: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:50.)
  c32 = torch.tensor([1+2j, 3+4j], dtype=torch.complex32)


In [ ]:
import torch

# Determine the device: GPU if available, otherwise CPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Example: creating a tensor of measurements with specific dtype, device, and gradient tracking
measurement_readings = torch.tensor(
    [1.5, 2.5, 3.5],
    dtype=torch.bfloat16,    # 16-bit brain floating point
    device=device,           # place tensor on the chosen device
    requires_grad=True       # enable autograd

In [6]:
import torch

def tensor_comedy_club():
    """
    A one-stop, funny showcase of tensor ops in PyTorch:
    - Addition
    - Multiplication
    - Subtraction (with reassignment)
    - Using torch.* funcs
    - Element-wise ops
    """

    # ——————————————————————————————
    # 1) Start with some “galaxy scores”
    galaxy_scores = torch.tensor([4, 8, 15, 16, 23, 42])
    # galaxy_scores: tensor([ 4,  8, 15, 16, 23, 42])

    # ——————————————————————————————
    # 2) Add a cosmic constant (+5)
    uplifted = galaxy_scores + 5
    # uplifted:      tensor([ 9, 13, 20, 21, 28, 47])

    # ——————————————————————————————
    # 3) Multiply by warp factor (×3)
    warp_multiplied = galaxy_scores * 3
    # warp_multiplied: tensor([ 12,  24,  45,  48,  69, 126])

    # ——————————————————————————————
    # 4) Originals stay the same until reassigned!
    # galaxy_scores still: tensor([ 4,  8, 15, 16, 23, 42])

    # ——————————————————————————————
    # 5) Subtract alien tax (–2) and reassign
    galaxy_scores = galaxy_scores - 2
    # galaxy_scores now: tensor([ 2,  6, 13, 14, 21, 40])

    # ——————————————————————————————
    # 6) Add star bonus (+10) and reassign
    galaxy_scores = galaxy_scores + 10
    # galaxy_scores now: tensor([12, 16, 23, 24, 31, 50])

    # ——————————————————————————————
    # 7) Use torch.multiply() to triple them
    triple_torch = torch.multiply(galaxy_scores, 3)
    # triple_torch: tensor([ 36,  48,  69,  72,  93, 150])

    # ——————————————————————————————
    # 8) Element-wise square (score × itself)
    galaxy_squared = galaxy_scores * galaxy_scores
    # galaxy_squared: tensor([ 144,  256,  529,  576,  961, 2500])

    return {
        "uplifted": uplifted,
        "warp_multiplied": warp_multiplied,
        "final_scores": galaxy_scores,
        "triple_torch": triple_torch,
        "galaxy_squared": galaxy_squared
    }


if __name__ == "__main__":
    results = tensor_comedy_club()
    # Uncomment to print live:
    for name, t in results.items():
      print(f"{name}: {t}")

uplifted: tensor([ 9, 13, 20, 21, 28, 47])
warp_multiplied: tensor([ 12,  24,  45,  48,  69, 126])
final_scores: tensor([12, 16, 23, 24, 31, 50])
triple_torch: tensor([ 36,  48,  69,  72,  93, 150])
galaxy_squared: tensor([ 144,  256,  529,  576,  961, 2500])
