In [1]:
import torch

# Set a seed to make results reproducible
torch.manual_seed(42)

# Generate a tensor with random values uniformly from [0, 1)
rand_tensor = torch.rand(3, 4)
print("Random tensor (uniform [0, 1)):")
print(rand_tensor)

# Generate a tensor with random values from a normal distribution (mean=0, std=1)
randn_tensor = torch.randn(3, 4)
print("\nRandom tensor (normal distribution N(0,1)):")
print(randn_tensor)

# Generate a tensor with random integers between 0 and 10
randint_tensor = torch.randint(low=0, high=10, size=(3, 4))
print("\nRandom integer tensor (0 to 9):")
print(randint_tensor)

# Create a random tensor with the same shape as another tensor
base_tensor = torch.ones(2, 2)
same_shape_random = torch.rand_like(base_tensor)
print("\nRandom tensor with same shape as base_tensor:")
print(same_shape_random)

# Create a general random tensor of size (3, 4) and check dtype
random_tensor = torch.rand(size=(3, 4))
print("\nAnother random tensor (3x4) and its dtype:")
print(random_tensor)
print("Dtype:", random_tensor.dtype)

# Create a random tensor simulating an image of shape (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
print("\nRandom image-like tensor (224, 224, 3):")
print("Shape:", random_image_size_tensor.shape)
print("Number of dimensions:", random_image_size_tensor.ndim)

Random tensor (uniform [0, 1)):
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Random tensor (normal distribution N(0,1)):
tensor([[ 2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898],
        [-0.9890,  0.9580,  1.3221,  0.8172]])

Random integer tensor (0 to 9):
tensor([[9, 6, 2, 0],
        [6, 2, 7, 9],
        [7, 3, 3, 4]])

Random tensor with same shape as base_tensor:
tensor([[0.7539, 0.1952],
        [0.0050, 0.3068]])

Another random tensor (3x4) and its dtype:
tensor([[0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278]])
Dtype: torch.float32

Random image-like tensor (224, 224, 3):
Shape: torch.Size([224, 224, 3])
Number of dimensions: 3


In [3]:
import torch

# Create a tensor filled with zeros
zero_tensor = torch.zeros(2, 3)
print("Zero tensor (2x3):")
print(zero_tensor)

# Create a tensor filled with ones
one_tensor = torch.ones(2, 3)
print("\nOne tensor (2x3):")
print(one_tensor)

# Create a tensor of ones with the same shape as another tensor
base = torch.rand(4, 4)
ones_like_base = torch.ones_like(base)
print("\nTensor of ones with same shape as base:")
print(ones_like_base)

# Create a tensor of all zeros using the size keyword
zeros = torch.zeros(size=(3, 4))
print("\nZeros tensor using size=(3, 4):")
print(zeros)
print("Dtype:", zeros.dtype)

# Create a tensor of all ones using the size keyword
ones = torch.ones(size=(3, 4))
print("\nOnes tensor using size=(3, 4):")
print(ones)
print("Dtype:", ones.dtype)

torch.ones((2, 2), dtype=torch.float64, device='cpu') #device='cuda'

Zero tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

One tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor of ones with same shape as base:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Zeros tensor using size=(3, 4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Dtype: torch.float32

Ones tensor using size=(3, 4):
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Dtype: torch.float32


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [4]:
import torch

# Matrix multiplication using torch.mm (2D only)
A = torch.tensor([[1., 2.], [3., 4.]])   # shape: (2, 2)
B = torch.tensor([[5., 6.], [7., 8.]])   # shape: (2, 2)
mm_result = torch.mm(A, B)
print("Result using torch.mm:")
print(mm_result)

# Same operation using @ (matmul)
matmul_result = A @ B
print("\nResult using @ operator:")
print(matmul_result)

# Using torch.matmul (supports >2D)
C = torch.randn(3, 2, 4)  # batch of 3 matrices (2x4)
D = torch.randn(3, 4, 5)  # batch of 3 matrices (4x5)
batch_result = torch.matmul(C, D)
print("\nBatch matrix multiplication with torch.matmul:")
print(batch_result.shape)  # Expected: (3, 2, 5)

# Using torch.bmm for batched 3D matrix multiplication (more strict)
E = torch.randn(10, 2, 3)  # 10 batches of 2x3
F = torch.randn(10, 3, 4)  # 10 batches of 3x4
bmm_result = torch.bmm(E, F)
print("\nBatch multiplication with torch.bmm:")
print(bmm_result.shape)  # Expected: (10, 2, 4)

# Using einsum for custom matrix operations
G = torch.randn(2, 3)
H = torch.randn(3, 4)
einsum_result = torch.einsum('ik,kj->ij', G, H)
print("\nResult using torch.einsum:")
print(einsum_result)

Result using torch.mm:
tensor([[19., 22.],
        [43., 50.]])

Result using @ operator:
tensor([[19., 22.],
        [43., 50.]])

Batch matrix multiplication with torch.matmul:
torch.Size([3, 2, 5])

Batch multiplication with torch.bmm:
torch.Size([10, 2, 4])

Result using torch.einsum:
tensor([[ 0.7642, -2.4521,  0.5980,  4.7121],
        [-0.8557,  1.3260, -1.5621, -3.2223]])


In [6]:
import torch
import time

def demo_matrix_ops(tensor1, tensor2):
    print("Tensor A shape:", tensor1.shape)
    print("Tensor B shape:", tensor2.shape)

    print("\n=== Element-wise Multiplication ===")
    try:
        elementwise = tensor1 * tensor2
        print(elementwise)
    except RuntimeError as e:
        print("Element-wise multiplication failed:", e)

    print("\n=== Matrix Multiplication using torch.matmul() ===")
    try:
        matmul_result = torch.matmul(tensor1, tensor2)
        print(matmul_result)
    except RuntimeError as e:
        print("Matrix multiplication failed:", e)

    print("\n=== Matrix Multiplication using @ operator ===")
    try:
        at_result = tensor1 @ tensor2
        print(at_result)
    except RuntimeError as e:
        print("Matrix multiplication with @ failed:", e)

    print("\n=== Manual Multiplication (DO NOT DO THIS!) ===")
    if tensor1.shape == tensor2.shape and tensor1.ndim == 1:
        start = time.time()
        value = 0
        for i in range(len(tensor1)):
            value += tensor1[i] * tensor1[i]
        end = time.time()
        print("Manual result:", value)
        print("Time taken: {:.6f} seconds".format(end - start))
    else:
        print("Manual loop skipped — only works for 1D tensors of equal shape.")

    print("\n=== Timing torch.matmul() ===")
    try:
        start = time.time()
        torch.matmul(tensor1, tensor2)
        end = time.time()
        print("Time taken: {:.6f} seconds".format(end - start))
    except:
        print("Timing skipped — incompatible shapes.")

A = torch.randn(3, 2)
B = torch.randn(2, 4)

demo_matrix_ops(A, B)

vec = torch.randn(10000)
demo_matrix_ops(vec, vec)


%timeit torch.matmul(A, B)

Tensor A shape: torch.Size([3, 2])
Tensor B shape: torch.Size([2, 4])

=== Element-wise Multiplication ===
Element-wise multiplication failed: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

=== Matrix Multiplication using torch.matmul() ===
tensor([[ 0.7468,  0.9281,  1.0435, -0.0170],
        [ 1.7899,  1.4999,  1.9535, -0.0539],
        [ 1.0622,  1.7359,  1.7984, -0.0168]])

=== Matrix Multiplication using @ operator ===
tensor([[ 0.7468,  0.9281,  1.0435, -0.0170],
        [ 1.7899,  1.4999,  1.9535, -0.0539],
        [ 1.0622,  1.7359,  1.7984, -0.0168]])

=== Manual Multiplication (DO NOT DO THIS!) ===
Manual loop skipped — only works for 1D tensors of equal shape.

=== Timing torch.matmul() ===
Time taken: 0.000019 seconds
Tensor A shape: torch.Size([10000])
Tensor B shape: torch.Size([10000])

=== Element-wise Multiplication ===
tensor([0.4443, 0.2601, 0.2299,  ..., 0.7400, 1.5702, 1.0573])

=== Matrix Multiplication using torch.matmu

In [8]:
import torch

# Create a random tensor
tensor = torch.rand(3, 4)
print("Original Tensor:")
print(tensor)

# Find the minimum value
min_value = torch.min(tensor)
print("\nMinimum value:")
print(min_value)

# Find the maximum value
max_value = torch.max(tensor)
print("\nMaximum value:")
print(max_value)

# Compute the mean (average)
mean_value = torch.mean(tensor)
print("\nMean value:")
print(mean_value)

# Compute the sum
sum_value = torch.sum(tensor)
print("\nSum of all values:")
print(sum_value)

# Compute the mean across each row (dim=1)
row_mean = torch.mean(tensor, dim=1)
print("\nMean across each row:")
print(row_mean)

Original Tensor:
tensor([[0.5326, 0.6296, 0.4862, 0.6644],
        [0.2369, 0.1999, 0.1373, 0.5334],
        [0.7350, 0.0626, 0.7710, 0.7017]])

Minimum value:
tensor(0.0626)

Maximum value:
tensor(0.7710)

Mean value:
tensor(0.4742)

Sum of all values:
tensor(5.6906)

Mean across each row:
tensor([0.5782, 0.2769, 0.5676])


In [9]:
import torch

# Original tensor of shape (2, 3)
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print("Original Tensor:")
print(tensor)

# Reshape to (3, 2)
reshaped = tensor.view(3, 2)
print("\nReshaped Tensor (3x2):")
print(reshaped)

# Stack tensors along a new dimension
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
stacked = torch.stack((t1, t2), dim=0)
print("\nStacked Tensor along dim=0:")
print(stacked)

# Squeeze a tensor (remove dimensions of size 1)
tensor_with_extra_dim = torch.zeros(1, 3, 1, 5)
squeezed = torch.squeeze(tensor_with_extra_dim)
print("\nSqueezed Tensor (removed size-1 dims):")
print(squeezed.shape)

# Unsqueeze a tensor (add a dimension of size 1)
t = torch.tensor([10, 20, 30])
unsqueezed = torch.unsqueeze(t, dim=0)
print("\nUnsqueezed Tensor (added dim=0):")
print(unsqueezed.shape)

# Permute dimensions of a tensor
permuted = tensor.permute(1, 0)
print("\nPermuted Tensor (swapped dims 0 and 1):")
print(permuted)

Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Reshaped Tensor (3x2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Stacked Tensor along dim=0:
tensor([[1, 2, 3],
        [4, 5, 6]])

Squeezed Tensor (removed size-1 dims):
torch.Size([3, 5])

Unsqueezed Tensor (added dim=0):
torch.Size([1, 3])

Permuted Tensor (swapped dims 0 and 1):
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [10]:
import torch

# Create a sample tensor
tensor = torch.tensor([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])
print("Original Tensor:")
print(tensor)

# Select a specific element (row 1, column 2)
single_value = tensor[1, 2]
print("\nElement at row 1, col 2:")
print(single_value)

# Select an entire row
row = tensor[0]
print("\nFirst row:")
print(row)

# Select an entire column (all rows, column 1)
column = tensor[:, 1]
print("\nSecond column:")
print(column)

# Slice multiple rows and columns
sub_tensor = tensor[0:2, 1:]
print("\nSliced Tensor (rows 0-1, cols 1-2):")
print(sub_tensor)

# Fancy indexing using a list of indices
fancy = tensor[[0, 2], [1, 2]]  # picks (0,1) and (2,2)
print("\nFancy indexing (positions (0,1) and (2,2)):")
print(fancy)

# Boolean masking
mask = tensor > 50
print("\nBoolean mask (values > 50):")
print(mask)

masked = tensor[mask]
print("Values > 50:")
print(masked)

Original Tensor:
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

Element at row 1, col 2:
tensor(60)

First row:
tensor([10, 20, 30])

Second column:
tensor([20, 50, 80])

Sliced Tensor (rows 0-1, cols 1-2):
tensor([[20, 30],
        [50, 60]])

Fancy indexing (positions (0,1) and (2,2)):
tensor([20, 90])

Boolean mask (values > 50):
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Values > 50:
tensor([60, 70, 80, 90])
